### ISSUE TITLE
No results being returned on RSS or JSON

### ISSUE THREAD

**Issue by BrittaSloane** [tweetledee/tweetledee#39]
PHP Version: 5.4.25
TweetleDee version: 0.4.0
Error Messages: None (but have debug turn on in file homerss.php)
Error description: Have installed and got the validation error a few times, then it just... went away. Didn't update anything in particular to get it gone.
For homerss.php I can see the RSS page in Firefox and am getting no debug messages - but there is absolutely nothing listed.
I've also tried other variables such as trying to pull a user's timeline and these are also not working - I'm getting no results at all. 
In Chrome trying the same URL as the URL that I gave you the error image for I get an error message. This doesn't change whether I've got debug set to 1 or not.
![twitter homerss php results](https://cloud.githubusercontent.com/assets/7111625/2563703/1b59d940-b888-11e3-9a10-b59aff00a591.JPG)
![chrome homerss php error message](https://cloud.githubusercontent.com/assets/7111625/2563709/46bf45b6-b888-11e3-9f24-1e9f07f32bbc.JPG)

**Comment by glubsy** [comment]
Thanks @kelcya I had the same issue with PHP 7.0 and had to install the php-mbstring package too.
