### ISSUE TITLE
Response code 0.

### ISSUE THREAD

**Issue by goelanshul** [tweetledee/tweetledee#54]
Hi Chris,
I was getting response code 0 all the time with OAuth module.
On Debugging, found out that setting 'curl_ssl_verifypeer' = false is the cause behind it.
For me , it worked by removing that assignment. 
Please fix the same in repo as well so that other's don't face the issue.

**Comment by chrissimpkins** [comment]
Thank you!

**Comment by rodrigoaguilera** [comment]
I think this has been fixed
