### ISSUE TITLE
Sometimes, images from one tweet are used as images for next tweets

### ISSUE THREAD

**Issue by Riduidel** [tweetledee/tweetledee#56]
it often happens that the image used in one tweet is used for the next tweet displaying another image, which makes things rather confusing.

**Comment by rodrigoaguilera** [comment]
I created a pull request. the "sometimes" part of the bug is that the image was not filled in case the tweet was a retweet so the code took the pic from the last tweet that had an image.

**Comment by Riduidel** [comment]
👍 
@chrissimpkins  what is the effort to integrate this PR ?

**Comment by rodrigoaguilera** [comment]
FYI I am making more changes in my fork but the code repetition in this project is so big that I feel that I should first propose a refactor.

**Comment by chrissimpkins** [comment]
Quite honestly I won't have the time to manage any of these issues.  You are more than welcome to assume control of the code repository and develop away or create your own fork and I can point to it.   

Glad to hear there is ongoing interest in development.

**Comment by chrissimpkins** [comment]
@rodrigoaguilera @Riduidel let me know if either of you are interested in becoming the project maintainer.

**Comment by rodrigoaguilera** [comment]
Yes, definitely. I even love the name of the project 😀

I feel that the option that will give more liberty is to start working from my fork. Or a new org fork if @riduidel is interested.

Not to mention you will still be credited for your great work.

Can I ask why you don't use this anymore or lost interest on the project?

I think reading twitter on RSS is awesome.

**Comment by chrissimpkins** [comment]
Change in my job early last year led to elimination of my time for my open source work unfortunately.  I care very much about all of my projects and love to see that there could be further development and improvements by others down the road.  That's one of the great benefits of open source work!

Let me know when you get your repo to a stage where you are ready for me to point to it as the current active development version of the work.  There have been a number of contributors to the project.  I suggest that you include all other contributors as equals if you intend to acknowledge my contributions in your fork.   The names are on the website and believe in the README (sorry on my phone and not looking at it at the moment).

**Comment by chrissimpkins** [comment]
We can change the website too.  This has been around for a few years and there are links out there to the repo that you will want to have re routed to your source.

**Comment by Riduidel** [comment]
Well, I don't have the time/skill set required to maintain Tweetledee. So, @rodrigoaguilera ,you can consider yourself the future maintainer :-) (I will only provide some testing)

**Comment by Riduidel** [comment]
@rodrigoaguilera I'm trying to take a look at your code to add support for Twitter new 280 characters limitation. Is there any way to join you ? I would like to know which branch has your image support feature ?

**Comment by rodrigoaguilera** [comment]
I'm sorry I didn't followed up on your proposoal.

I opened a Pull request in this project.


the branch with the fixes is the master at
https://github.com/rodrigoaguilera/tweetledee

**Comment by chrissimpkins** [comment]
There is an open PR on this repository to support the 280 characters as well.  #59 

Perhaps we consolidate this work into a branch and consider making it the default with a merge to master when we have confirmed that we are ok with (1) rate limits; (2) backwards compatibility, lack thereof

See conversation in that PR thread from the work submitted by @MageFroh

**Comment by chrissimpkins** [comment]
@rodrigoaguilera Rodrigo, are you maintaining a fork of this repository?  If so, perhaps @MageFroh work would be best suited there and we can begin to deprecate this repository and direct traffic your way assuming that you intend to continue development.

**Comment by chrissimpkins** [comment]
Alternatively (and this applies to you as well @MageFroh), I would be happy to transition this repo to anyone who wants to take over maintainer duties.  I honestly don't have the time for it and it seems that there is still some interest in development out there.  I would like to support future work by putting this in the hands of someone who will continue development and wants to maintain it.

**Comment by rodrigoaguilera** [comment]
I think the ideal scenario is a co-maintainership between the people who use it daily and have some PHP abilities to fix issues.

I enjoy the use of this project everyday and I have improvements in mind like a display of tweets with many pics and videos.


I will happily take some more responsibility over this project. What do you think @MageFroh ?
