### ISSUE TITLE
error while checking "http://[yourdomain]/tweetledee/homejson.php" and "http://[yourdomain]/tweetledee/userrss.php"

### ISSUE THREAD

**Issue by vigneshrvicky** [tweetledee/tweetledee#58]
I download tweetledee zip file from http://chrissimpkins.github.io/tweetledee/usage.html and locate in D drive on my PC
tweetle version:0.4.2 (chrissimpkins-tweetledee-v0.4.2-1-gc63daca.zip)

After finishing all the instructions given by you.I try Check "http://[yourdomain]/tweetledee/userrss.php"
and I got The error.The error is listed bellow

XML Parsing Error: syntax error
Location: http://example.com/tweetledee/homejson.php
Line Number 1, Column 1:
<!doctype html>
^

**Comment by chrissimpkins** [comment]
To confirm, you are using a local PHP server to attempt this?

https://stackoverflow.com/questions/1678010/php-server-on-local-machine

**Comment by rodrigoaguilera** [comment]
Closed because of inactivity
