### ISSUE TITLE
New maintainership structure

### ISSUE THREAD

**Issue by rodrigoaguilera** [tweetledee/tweetledee#60]
A discussion happened here 
https://github.com/chrissimpkins/tweetledee/issues/56
about how the current maintainer can no longer be in charge so I offered to help.

We think the best way forward is to create a "tweetledee" org on github and transfer the permissions.

Let's hope @magefroh joins later.

**Comment by chrissimpkins** [comment]
Thanks for offering to maintain this repository @rodrigoaguilera!  I am in complete agreement that someone else would be better able to maintain and continue development here.

I have transferred the chrissimpkins/tweetledee repository to tweetledee Github organization account (as tweetledee/tweetledee) and will send you an invite so that we can set you as the admin on the repository.  This will provide you with full read/write access, invite access for new organization members, and the ability to transfer the repository elsewhere if a different account is preferable.

**Comment by rodrigoaguilera** [comment]
I will edit the composer.json to reflect this change.
I hope you still want to be listed as an author there.

Maybe there is another action for you to do when that change to composer.json happens by marking the old one as abandoned so tweetledee/tweetledee is the canonical one.

It happened for the robo project.
https://packagist.org/packages/consolidation/robo
https://packagist.org/packages/codegyre/robo

**Comment by chrissimpkins** [comment]
I sent an invite to @rodrigoaguilera as Owner and to @MageFroh as member.  I will turn over the remainder of maintainer responsibilities to you.  If you have not managed an organization account previously, have a look at the current organization settings for member default privileges (including write access/repository move access/repo delete access) before you invite new members.

**Comment by chrissimpkins** [comment]
> I hope you still want to be listed as an author there.

Sure, that would be great. I created the project, provided a majority of the existing source, and maintained it for the last few years.  I would greatly appreciate it if you would be willing to keep me on the authors list for those contributions.

**Comment by chrissimpkins** [comment]
> Maybe there is another action for you to do when that change to composer.json happens by marking the old one as abandoned so tweetledee/tweetledee is the canonical one

Wow, I guess this has been around even longer than I recalled.  That commit is from five years ago.  I don't have any knowledge of Composer package management.  Do you know how to do this?

**Comment by rodrigoaguilera** [comment]
When you go to
https://packagist.org/packages/simpkins/tweetledee
And you are logged in there is an "Abandon" button.

I made things easy by creating 
https://packagist.org/packages/tweetledee/tweetledee

**Comment by chrissimpkins** [comment]
chrissimpkins/tweetledee was abandoned and it now points to tweetledee/tweetledee as the suggested replacement.  Let me know if anything else that you need from me on my end

**Comment by chrissimpkins** [comment]
Feel free to remove all of my maintainer metadata from the composer.json file so that packagist points to you

**Comment by chrissimpkins** [comment]
Transition appears to be complete. Feel free to downgrade my organization membership status.  I turn this over to you to keep chugging along.  Thanks Rodrigo and good luck!

**Comment by rodrigoaguilera** [comment]
Thank you for this great piece of code and keeping maintanership task responsibly.

**Comment by rodrigoaguilera** [comment]
With a new release made I think we can close this. Thanks again
