### ISSUE TITLE
hashtag entity replacements generating error

### ISSUE THREAD

**Issue by jools-r** [tweetledee/tweetledee#64]
I'm not sure if this is particular to my own situation or a more general problem (if the latter I would have expected it to have been noticed sooner).

I'm getting errors with hashtag replacement strings. The problem derives from the fact that – in my retrieved twitter timeline at least – the key for a hashtag entity is `text` and not `full_text`:

```json
"entities": {
      "hashtags": [
        {
          "text": "refugees",
          "indices": [
            42,
            62
          ]
        }
      ],
      "user_mentions": [
        {
          "screen_name": "Name",
          "name": "Name",
          "id": 542613011,
          "id_str": "542613011",
          "indices": [
            3,
            15
          ]
        },
````

EDIT: That seems to be corroborated by the [Twitter docs on entities objects](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object).

Hence `$value['full_text']` should be replaced with `$value['text']` on [line 60 of tmhUtilities.php](https://github.com/tweetledee/tweetledee/blob/master/tweetledee/tldlib/tmhUtilities.php#L69):

```php
$href = "<a href=\"https://twitter.com/search?q=%23{$value['text']}\"{$target}>#{$value['text']}</a>";
```

That resolves it for me.

**Comment by rodrigoaguilera** [comment]
Fixed in the master branch. Thanks for the report an the solution :)
