### ISSUE TITLE
Show all images of tweet

### ISSUE THREAD

**Issue by Riduidel** [tweetledee/tweetledee#66]
When tweet has more that one image embedded, only the first is used in tweetledee. Is it possible to have all images in tweetledee ?

**Comment by Riduidel** [comment]
I'll try to take a look at this during #hacktoberfest, will it be possible to have any help ?

**Comment by rodrigoaguilera** [comment]
Same as the other #hacktoberfest feature, this would be really interesting to have.

**Comment by Riduidel** [comment]
Daaaamn, it seems like there is only one image in twitter API content ....
No, wait,
in fact, all images are present, but not in `entities`, in `extended_entities` (as explained there https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/extended-entities-object)
