### ISSUE TITLE
Quoting another tweet should have the other tweet included in feed

### ISSUE THREAD

**Issue by Riduidel** [tweetledee/tweetledee#67]
Typically, for retweets, we only have an url displayed with no content in. Is it possible, even using an option, to have the retweeted text displayed ?

**Comment by Riduidel** [comment]
I plan to take a look at this during #hacktoberfest. Is it possible to have any help on that subject ?

**Comment by rodrigoaguilera** [comment]
I really love the feature but I will have a lot personal stuff going on during October so I won't be able to provide support, I can review PRs though.

I still use this project daily to read twitter and I have been delaying some cleaning for a few months now.

**Comment by Riduidel** [comment]
ok, so it seems like the "pure" retweets are correctly handled.
As an example, in `/tweetledee/homerss_nocache.php` there is the code

                if (isset($currentitem['retweeted_status'])) :
                    $avatar = $currentitem['retweeted_status']['user']['profile_image_url'];
                    $rt = '&nbsp;&nbsp;&nbsp;&nbsp;[<em style="font-size:smaller;">Retweeted by ' . $currentitem['user']['name'] . ' <a href=\'http://twitter.com/' . $currentitem['user']['screen_name'] . '\'>@' . $currentitem['user']['screen_name'] . '</a></em>]';
                    $tweeter =  $currentitem['retweeted_status']['user']['screen_name'];
                    $fullname = $currentitem['retweeted_status']['user']['name'];
                    $tweetTitle = $currentitem['retweeted_status']['full_text'];

Which is precisely here to show retweets in a specific fashion.
So I'll try to take a look at link expansion in tweets ... which will undoubtly prove to be a little more complicated 🙂

**Comment by Riduidel** [comment]
Daaamn, it seems like embedded tweets are stored in `['entities']['url']` objects.
So the best way is to call [`/show/:id`](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id) with embedded tweet id.
But I guess it will require having the config more accessible, or at least the cache and the twitter api accessible through the same interface, which will again be a nice refactoring 😅

**Comment by Riduidel** [comment]
That's ok now; Obviously I've commited (again) my tweetledee keys and remvoed them after.

**Comment by Riduidel** [comment]
Please notice that when #73 will be merged in master, some work (hopefully not so much) will have to be done in this branch.

**Comment by rodrigoaguilera** [comment]
I am leaving this open because the documentation needs to be updated with the new `rl` query parameter.

@Riduidel Do you want to take on that task too?

**Comment by Riduidel** [comment]
Yes, you can assign that to me.

**Comment by rodrigoaguilera** [comment]
Great!

Thank you for making tweetledee amazing :)

**Comment by Riduidel** [comment]
Well, as I use it on a 2-hour crontab basis, I do consider it too useful to not maintain it correctly :-)
