### ISSUE TITLE
"user_timeline connection failure" when I use searchrss.php

### ISSUE THREAD

**Issue by ruleroller** [tweetledee/tweetledee#84]
release: 0.5.2

I tried the url like "xxx.xxx.xxx/tweetledee/tweetledee/searchrss.php?q=dog", it tells "user_timeline connection failure".

Then I tried "xxx.xxx.xxx/tweetledee/tweetledee/favoritesrss.php", "xxx.xxx.xxx/tweetledee/tweetledee/homerss.php", they works, show the items.

0.5.1 and before's searchrss.php works btw.

**Comment by rodrigoaguilera** [comment]
There has been a lot of refactoring between versions and probably something was forgotten along the way. I will try to have a look this week.

Thank you for testing and it

**Comment by rodrigoaguilera** [comment]
Can you deploy the new release and close this issue if the bug is solved?

**Comment by ruleroller** [comment]
@rodrigoaguilera Thanks, I just git pull to the latest, it works now. 
the "tweetledee_keys.php" need _**?>**_ in last line.

**Comment by rodrigoaguilera** [comment]
Please report if you find more bugs.

From https://www.php.net/manual/en/language.basic-syntax.phptags.php

> If a file contains only PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.
