### ISSUE TITLE
Use https for avatar img src?

### ISSUE THREAD

**Issue by jools-r** [tweetledee/tweetledee#89]
Currently the avatar img src of a tweet has a `http://` link resulting in a mix of http and https warning for https sites.

It's easily resolved by replacing instances of `[profile_image_url]` with  `[profile_image_url_https]`.

That appears in lines [23](https://github.com/tweetledee/tweetledee/blob/29748a1f637650ca60b0351689024a1d48369b28/tweetledee/tldlib/renderers/rss.php#L23) and [32](https://github.com/tweetledee/tweetledee/blob/29748a1f637650ca60b0351689024a1d48369b28/tweetledee/tldlib/renderers/rss.php#L32) of `/tldlib/renderers/rss.php` and also in the respective feed variants (though changing the latter doesn't seem to have an effect).

Is there any reason why this might not be a good idea to adopt in all cases? https `src` links in an http site are not a problem and I presume twitter will be providing `[profile_image_url_https]` consistently. If there's a worry that twitter might deprecate that at the some point when https becomes the norm, one could always code it to fall back to `[profile_image_url]`should it not exist.

*Note: I've not been able to check if the http/https aspect is a problem for inline images in tweets but it may be worth checking there too.*

**Comment by scysys** [comment]
Was also here for this.
Thanks @jools-r :)

**Comment by rodrigoaguilera** [comment]
Fixed https://github.com/tweetledee/tweetledee/commit/43ce012233581aa47edb8edf3ab37cf15720913b
