### ISSUE TITLE
Undefined index: type in parametersProcessing.php

### ISSUE THREAD

**Issue by glubsy** [tweetledee/tweetledee#90]
I get a lot of these errors lately:
```
2019/12/15 19:58:52 [error] 25954#25954: *1182 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: type in /tweetledee/tweetledee/tldlib/parametersProcessing.php on line 110  
PHP message: PHP Notice:  Undefined index: type in /tweetledee/tweetledee/tldlib/parametersProcessing.php on line 119" while reading response header from upstream, client: 192.168.0.19, server: _, request: "GET /tweetledee/userrss.php?user=test&c=200&xrp=0&xrt=0&cache_interval=300 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.0.18:80"  
```

Not familiar with the code, but from what I've gathered, it might be because [some parameters do not have a "TYPE" member](https://github.com/tweetledee/tweetledee/blob/master/tweetledee/tldlib/parametersProcessing.php#L31), and thus this is failing? Please correct me if I'm wrong.

[error comes from line 110 or 119](https://github.com/tweetledee/tweetledee/blob/master/tweetledee/tldlib/parametersProcessing.php#L110).

Thanks!

**Comment by rodrigoaguilera** [comment]
I just pushed a quick check for the TYPE to avoid warnings.
https://github.com/tweetledee/tweetledee/commit/52b60d4ce6c93bcce66f2e844145c105bd14b3db
That piece of code needs some work.


I prefer to wait a bit for a release. Do you need it?

**Comment by glubsy** [comment]
Thanks for the fix!

I use the git repo, so personally I don't need a proper release just for that.
