### ISSUE TITLE
Latest redesign of Twitter makes retweets impossible to open

### ISSUE THREAD

**Issue by Riduidel** [tweetledee/tweetledee#91]
Since latest Twitter redesign, all retweets appear as truncated.
Take as an example https://twitter.com/GeePawHill/statuses/1266249500177297408

In previous Twitter UI this would open the full tweet (in other words the full text would show up).
Since latest Twitter UI redesign and API change, tweet now appear as truncated. Why ?

Wheregoes provide a view of the route taken by this request which gives the following endpoints list

1. https://twitter.com/GeePawHill/statuses/1266249500177297408 🍪 301 Redirect
1. https://twitter.com/aheritier/status/1266249500177297408 🍪 302 Redirect
1. https://twitter.com/GeePawHill/status/1265358897960886278 🍪 

Notice that directly opening the final URL will show the full tweet.

So we should change tweet rendering to directly display last url.

**Comment by rodrigoaguilera** [comment]
In fact I was bugged by this and then I started to use the invidition extension on firefox to redirect all twitter links to nitter.net.

Thanks for reporting!
