### ISSUE TITLE
User with a username that end with underscore not work properly

### ISSUE THREAD

**Issue by Ogekuri** [tweetledee/tweetledee#94]
User with a username that end with underscore not work properly.

I've tries to create 2 feeds from (2 differ account):
[@SplatoonNews_](https://twitter.com/SplatoonNews_)
[@SplatoonNews](https://twitter.com/SplatoonNews)

But same content (probably from cache) is provided.

Any support to found a workaround is very appreciated.

Thanks!
Francesco.

**Comment by Ogekuri** [comment]
Just to confirm that _userjson_pp_nocache.php_ works and provide 2 differ contents correclty.

The issue is only with _userrss.php_.

Ciao!
Francesco.

**Comment by Ogekuri** [comment]
Ok, I've found a "workaround".

I have removed '**"_"**' from _sanitize_ in _tldCache.php_ on line 139.

Ciao!
Francesco.

**Comment by rodrigoaguilera** [comment]
No Pull Request?

**Comment by Ogekuri** [comment]
I really don't know if it can work in all cases, now the cache filenames are changed from this:

```
httpsapitwittercom11statusesusertimelinejson11001splatoonnews
```

to this:

```
httpsapitwittercom11statusesuser_timelinejson11001splatoonnews
httpsapitwittercom11statusesuser_timelinejson11001splatoonnews_

```

Honeslty I don't know if it's just a side-effects or not.

For sure, the cache folder will not be back compatible so the upgrade will cause a cache data-loss end a flood to twitter's server.

Ciao,
Francesco.
